export const ADD_CHAT = "CHAT::ADD_CHAT";
export const REMOVE_CHAT = "CHAT::REMOVE_CHAT";
export const ADD_NOTIFICATION = "CHAT::ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "CHAT::REMOVE_NOTIFICATION";